name: Building

on: push

jobs:
  urecomm-front-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.19.0"

      - name: Install packages & build project 
        run: |
              npm install
              npm run build
      
      - name: Tests
        run: |
              npm run test